version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
