version: '3.8'
services:
  redis:
    container_name: redis-server
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes


  apiuserv1:
    container_name: apiuserv1
    build: .
    ports:
      - "8082:80"
    depends_on:
      - redis
    environment:
      - SERVER_PORT=80
      - SPRING_DATA_REDIS_HOST=redis-server
      - SPRING_DATA_REDIS_PORT=6379
      - SECURITY_JWT_SECRET=5b87002b7468120df2e1dbbd223caf54e9cfbf0800f084380bc1d1d84f747bb897a9bfae51b868a0cf2d0f5094c0e07a07f6a49f2fdb395c37e7186cab6d00f0
      - SECURITY_JWT_EXPIRATION=86400000
      - SECURITY_JWT_ROL=ADMIN
      - VALIDATION_PASSWORD_PATTERN=^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$ # Minimo 8 caracteres, al menos una letra, un número y un carácter especial
volumes:
  redis_data:


