spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  r2dbc:
    url: r2dbc:h2:mem:///db
    username: sa
    password:
  application:
    name:
      api-user-v1
  webflux:
    base-path: /api/user-v1
springdoc:
  info:
    version: '@project.version@'
    title: '@project.artifactId@'
    description: '@project.description@'
    servers:
      - 'http://localhost:8082/'
      - 'http://localhost/'
  api-docs:
    path: /openapi
    yaml:
      enabled: true    
  swagger-ui:
    enabled: false